databases:
  - name: twitter_django
    databaseName: twitter_django
    user: twitter_django

services:
  - type: web
    name: twitter_django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn twitter_django.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: twitter_django
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4