# Generated by Django 4.1.3 on 2022-11-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=300)),
                ('tweets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.tweet')),
            ],
        ),
    ]
